version: "2"
services:
  app:
    image: golang:1.9.2
    ports:
      - "9898:9898"
    volumes:
      - .:/go/src/plotbot-server
    working_dir: /go/src/plotbot-server
    command: bash -c "go get github.com/golang/dep/cmd/dep && dep ensure && go build . && ./plotbot-server"
    restart: unless-stopped
